sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk7
script:
- sbt -Dfile.encoding=UTF8 -no-colors ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  slack:
    secure: XmZkluyXt6jkoWoNIMKMWS5enN188AeMiMs8bPguT+ZCbRGIFDCqxSzg+jCqaUbziE+A+ee2LzOoCkKtCIeAbJxpUzg5rojgaFE4K4V62iDP5oUoDQj5UkJ1vzn1aTKNc3tYY/LFR0ktgVKRq3CimvIJhjW5TQvv6WeN4LH0bs1ESz2QkMsEqmUi0ig8KNEydOy5di1wP28/4cvo3zeogZFtm0O2IQjmwuaZI+QDf8Z/zkekO11RlEUr4LtG5NkmTBVoKNhfxVmqaGpezUG7OiXTQrEFgDoxTuXqLpB6WDTkzLgnwRdcr8rtjYh7s5o7UlPqyB2FdkRB6uPnqRs2FVLtnPCXmZR7lLhDUUrq2v8rKGK2gJFmnSJwuR6rGngvw6T21uE6oWIxogCH7z+54kBdscsDsIrGr1OG0sMQshFOH+jFfMrKEkqA29YHnCG55+mlk0PtQ9IHCjdbzs6x8obRzeM0N81a3WWMBAzOb+RgYC4H+CzyLfyagR6bN4ekNLLulPLvxMx08fJCxhL/+Io5eACGMZ671+nM0W6S7PuMzDL2B9HRluOorP7Sdse9LxgffSc/hZWizpk3ibJDB9MA8+HXueXjFh9rbXIfvoky3FQrsI6swdyQFjH+ezx0IgfqeE7EtmlDgwqFPE9zFHKVR98DBs9eBIkCn7+Nar4=
